### ISSUE TITLE
auto complete location feature

### ISSUE THREAD

**Issue by NickWebber21** [NickWebber21/hackoh12o#2]
when someone starts typing in the starting point or destination it auto completes

**Comment by iankwiatko** [comment]
https://console.cloud.google.com/google/maps-apis/discovernow/autocomplete;filters=%7B%22useCaseFilters%22:%5B%5D,%22platformFilters%22:%5B%5D,%22codeTypeFilters%22:%5B%5D%7D?project=sylvan-mesh-439117-a2
